Repository nuuxcode/AirBnB_clone_v2, pull requests merged in 2023-09, with the labels that each got.

#1 Title: Added my name to AUTHORS
  AUTHORS
Labels: documentation, enhancement

#3 Fix string comparaison from is to ==
  console.py
  file.json
  models/__pycache__/__init__.cpython-311.pyc
  models/__pycache__/__init__.cpython-38.pyc
  models/__pycache__/amenity.cpython-311.pyc
  models/__pycache__/amenity.cpython-38.pyc
  models/__pycache__/base_model.cpython-311.pyc
  models/__pycache__/base_model.cpython-38.pyc
  models/__pycache__/city.cpython-311.pyc
  models/__pycache__/city.cpython-38.pyc
  models/__pycache__/place.cpython-311.pyc
  models/__pycache__/place.cpython-38.pyc
  models/__pycache__/review.cpython-311.pyc
  models/__pycache__/review.cpython-38.pyc
  models/__pycache__/state.cpython-311.pyc
  models/__pycache__/state.cpython-38.pyc
  models/__pycache__/user.cpython-311.pyc
  models/__pycache__/user.cpython-38.pyc
  models/base_model.py
  models/engine/__pycache__/__init__.cpython-311.pyc
  models/engine/__pycache__/__init__.cpython-38.pyc
  models/engine/__pycache__/file_storage.cpython-311.pyc
  models/engine/__pycache__/file_storage.cpython-38.pyc
  test_params_create
  tests/__init__.py
  tests/__pycache__/__init__.cpython-311.pyc
  tests/test_models/__pycache__/__init__.cpython-311.pyc
  tests/test_models/__pycache__/test_amenity.cpython-311.pyc
  tests/test_models/__pycache__/test_base_model.cpython-311.pyc
  tests/test_models/__pycache__/test_city.cpython-311.pyc
  tests/test_models/__pycache__/test_place.cpython-311.pyc
  tests/test_models/__pycache__/test_review.cpython-311.pyc
  tests/test_models/__pycache__/test_state.cpython-311.pyc
  tests/test_models/__pycache__/test_user.cpython-311.pyc
  tests/test_models/test_engine/__pycache__/__init__.cpython-311.pyc
  tests/test_models/test_engine/__pycache__/test_file_storage.cpython-311.pyc
Labels: bug, invalid

#4 Title: add gitignore file, add mysql setup for development
  .gitignore
  file.json
  models/__pycache__/__init__.cpython-311.pyc
  models/__pycache__/__init__.cpython-38.pyc
  models/__pycache__/amenity.cpython-311.pyc
  models/__pycache__/amenity.cpython-38.pyc
  models/__pycache__/base_model.cpython-311.pyc
  models/__pycache__/base_model.cpython-38.pyc
  models/__pycache__/city.cpython-311.pyc
  models/__pycache__/city.cpython-38.pyc
  models/__pycache__/place.cpython-311.pyc
  models/__pycache__/place.cpython-38.pyc
  models/__pycache__/review.cpython-311.pyc
  models/__pycache__/review.cpython-38.pyc
  models/__pycache__/state.cpython-311.pyc
  models/__pycache__/state.cpython-38.pyc
  models/__pycache__/user.cpython-311.pyc
  models/__pycache__/user.cpython-38.pyc
  models/engine/__pycache__/__init__.cpython-311.pyc
  models/engine/__pycache__/__init__.cpython-38.pyc
  models/engine/__pycache__/file_storage.cpython-311.pyc
  models/engine/__pycache__/file_storage.cpython-38.pyc
  setup_mysql_dev.sql
  test_params_create
  tests/__pycache__/__init__.cpython-311.pyc
  tests/test_models/__pycache__/__init__.cpython-311.pyc
  tests/test_models/__pycache__/test_amenity.cpython-311.pyc
  tests/test_models/__pycache__/test_base_model.cpython-311.pyc
  tests/test_models/__pycache__/test_city.cpython-311.pyc
  tests/test_models/__pycache__/test_place.cpython-311.pyc
  tests/test_models/__pycache__/test_review.cpython-311.pyc
  tests/test_models/__pycache__/test_state.cpython-311.pyc
  tests/test_models/__pycache__/test_user.cpython-311.pyc
  tests/test_models/test_engine/__pycache__/__init__.cpython-311.pyc
  tests/test_models/test_engine/__pycache__/test_file_storage.cpython-311.pyc
Labels: enhancement

#5 Title: Task5 Delete object
  .gitignore
  models/engine/file_storage.py
Labels: enhancement

#6 Tasks/nuuxcode/task6
  console.py
  models/__init__.py
  models/amenity.py
  models/base_model.py
  models/city.py
  models/engine/db_storage.py
  models/engine/file_storage.py
  models/place.py
  models/review.py
  models/state.py
  models/user.py
Labels: bug, documentation, enhancement

#7 Title : Task6: add test file for task6 and 7, add unique to name stat…
  console.py
  models/base_model.py
  models/engine/db_storage.py
  models/state.py
  tests/test_script/script6.sh
  tests/test_script/script7.sh
Labels: bug, documentation, enhancement

#8 Tasks/fuzzworth/task07
  models/user.py
  tests/test_script/check7.sh
  tests/test_script/script7.sh
  tests/test_script/test
  tests/test_script/test_file.txt
Labels: documentation, enhancement

#9 Tasks/fuzzworth/task07
  models/user.py
Labels: bug, enhancement

#10 Tasks/fuzzworth/task07
  models/engine/db_storage.py
Labels: bug, enhancement

#11 Tasks/fuzzworth/task07
  models/user.py
Labels: bug, enhancement

#12 Title: Task8
  models/city.py
  models/place.py
  models/state.py
  models/user.py
Labels: enhancement

#13 Title: Task8 debugin checker
  models/place.py
Labels: bug

#14 Tasks/fix/fuzzworth/task08
  models/engine/db_storage.py
Labels: bug

#15 Title : adding test file task8,7 + testing without try except error
  .gitignore
  console.py
  models/base_model.py
  models/engine/db_storage.py
  tests/test_script/c6.sh
  tests/test_script/c7.sh
  tests/test_script/c8.sh
  tests/test_script/script7.sh
  tests/test_script/test
  tests/test_script/test_file.txt
Labels: bug, enhancement

#16 Title: Task10, fix pycodestyle
  main_place_amenities.py
  models/amenity.py
  models/engine/file_storage.py
  models/place.py
  models/state.py
  tests/test_models/test_base_model.py
  tests/test_models/test_engine/test_file_storage.py
  tests/test_script/c10.sh
Labels: enhancement

#17 Title: Fix output for task5 by adding Filestorage case for all classes
  models/amenity.py
  models/city.py
  models/place.py
  models/review.py
  models/state.py
  models/user.py
Labels: enhancement

#18 Title: fix Task2/Task8, improve do_create and init in basemodel
  .gitignore
  console.py
  main_delete.py
  models/base_model.py
Labels: bug, enhancement

#19 Tasks/fuzzworth/task09
  models/place.py
  models/review.py
  models/user.py
Labels: documentation, enhancement

#20 Title: Task1, Unittest
  models/base_model.py
  tests/test_console.py
  tests/test_models/test_amenity.py
  tests/test_models/test_base_model.py
  tests/test_models/test_city.py
  tests/test_models/test_engine/test_db_storage.py
  tests/test_models/test_engine/test_file_storage.py
  tests/test_models/test_place.py
  tests/test_models/test_review.py
  tests/test_models/test_state.py
  tests/test_models/test_user.py
Labels: bug, documentation, enhancement

#21 Title: fix pycodestyle
  console.py
  models/place.py
  test
  tests/test_console.py
  tests/test_models/test_base_model.py
  tests/test_models/test_engine/test_db_storage.py
  tests/test_models/test_engine/test_file_storage.py
Labels: bug, documentation, enhancement

#22 Title: debuging testing errors
  console.py
  models/state.py
Labels: bug

#23 Title: fixing more testing errors
  .gitignore
  tests/test_models/test_base_model.py
  tests/test_models/test_engine/test_file_storage.py
Labels: bug

#24 Title: fix pycodestyle
  main_delete.py
  models/amenity.py
  models/engine/db_storage.py
  models/place.py
  models/state.py
Labels: bug

#26 Title: fixing all testing errors, cleaning
  models/engine/db_storage.py
  tests/test_console.py
  tests/test_models/test_base_model.py
  tests/test_models/test_engine/test_db_storage.py
  tests/test_models/test_engine/test_file_storage.py
Labels: bug, documentation, enhancement
